### PR TITLE
Fix: Change Duke To Fridget

### LINKED ISSUE #37: Rename Duke and related content to Fridget

### PR DESCRIPTION
**Pull request by alvynben**
This pull request fixes #37 .

### CODE REVIEW

File: src/main/java/seedu/ui/Ui.java [hunk 1]
```diff
@@ -16,12 +16,19 @@ public Ui() {
...
+                + "   ad88              88           88                                    \n"
+                + "  d8\"                \"\"           88                             ,d     \n"
+                + "  88                              88                             88     \n"
+                + "MM88MMM  8b,dPPYba,  88   ,adPPYb,88   ,adPPYb,d8   ,adPPYba,  MM88MMM  \n"
+                + "  88     88P'   \"Y8  88  a8\"    `Y88  a8\"    `Y88  a8P_____88    88     \n"
+                + "  88     88          88  8b       88  8b       88  8PP\"\"\"\"\"\"\"    88     \n"
+                + "  88     88          88  \"8a,   ,d88  \"8a,   ,d88  \"8b,   ,aa    88,    \n"
+                + "  88     88          88   `\"8bbdP\"Y8   `\"YbbdP\"Y8   `\"Ybbd8\"'    \"Y888  \n"
+                + "                                       aa,    ,88                       \n"
+                + "                                        \"Y8bbdP\"                        ";
```
Comment (zonglun99) [inline src/main/java/seedu/ui/Ui.java:29]: Logo looks good

**Review by zonglun99 — COMMENTED** [review]
LGTM nice that you have already updated the regression testing

**Review by zonglun99 — APPROVED** [review]
